/* Default lab inventory (from the lab's "Senarai Inventori Komponen Optik" sheet plus the instruments named on 7 Oct 2026).
   status: use = can be used in this project, check = identify or measure first, no = not suitable. bom = BOM item(s) it can cover.
   Edits made on the Lab Inventory page are kept in the browser and can be synced to the private database. */
window.LAB_INVENTORY = {
  version: 2,
  items: [
    { id: 'L01', name: 'Polarizing cube beamsplitter, cage-mounted', part: 'CM1-PBS251', brand: 'Thorlabs', qty: '2', model: 'pbs', mp: {}, status: 'no', bom: 'O03',
      specs: '30 mm cage-cube-mounted polarizing beamsplitter cube, 420–680 nm, 8-32 and M4 adapters. Discontinued 21 Sep 2016.',
      role: 'Wrong band for 795 nm (the BOM needs the 620–1000 nm CM1-PBS252). Usable only with a visible alignment laser.', link: 'https://media.thorlabs.com/globalassets/items/c/cm/cm1/cm1-pbs251/cm1-pbs251.pdf?v=0116105842', loc: '', owner: '', notes: '' },
    { id: 'L02', name: 'Fixed lens mount, internally threaded, Ø1″', part: 'LMR1/M', brand: 'Thorlabs', qty: '12', model: 'lens', mp: {}, status: 'use', bom: 'O10, O14',
      specs: 'Holds Ø1″ optics with a retaining ring, internal threads, M4 (8-32) tap for Ø½″ posts, retaining ring included.',
      role: 'Lens mounts (5) and ND-filter holders (2) for the bench.', link: 'https://www.thorlabs.com/fixed-lens-mounts?pn=LMR1%2FM', loc: '', owner: '', notes: '' },
    { id: 'L03', name: 'Fixed lens mount with no retaining lip, SM1 thread', part: 'SMR1/M', brand: 'Thorlabs', qty: '3', model: 'lens', mp: {}, status: 'use', bom: 'O10',
      specs: 'Fixed mount for Ø1″ optics, internal SM1 threads, M4 (8-32) tap for Ø½″ posts; optics are held with two retaining rings (sold separately).',
      role: 'Spare lens or filter mounts; also holds SM1-threaded parts on either side.', link: 'https://www.thorlabs.com/fixed-lens-mounts?pn=SMR1%2FM', loc: '', owner: '', notes: '' },
    { id: 'L04', name: 'Rack-and-pinion rod clamp', part: 'M-340-RC', brand: 'Newport', qty: '', model: 'rodclamp', mp: {}, status: 'no', bom: '',
      specs: 'M6 thread, inside diameter 38.1 mm (Ø1.5″ rods).',
      role: 'Newport Ø1.5″ rod system, not our Ø½″ post system.', link: 'https://www.newport.com/p/M-370-RC', loc: '', owner: '', notes: '' },
    { id: 'L05', name: 'Rotary stage', part: '', brand: 'Edmund Scientific Co.', qty: '', model: 'rotstage', mp: {}, status: 'use', bom: 'O16',
      specs: 'Rotary movement, ±5° fine and 360° coarse, slide-fit guide, aluminium stage, metric micrometer drive.',
      role: 'Rotation mount for the Glan–Taylor polarizer (or a waveplate).', link: 'https://www.edmundoptics.com.sg/f/rotary-stages/13960/', loc: '', owner: '', notes: '' },
    { id: 'L06', name: 'FiberPort collimator / coupler, f = 18.4 mm', part: 'PAF-X-18-B', brand: 'Thorlabs', qty: '', model: 'fibcol', mp: {}, status: 'check', bom: 'L05',
      specs: 'FiberPort, FC/APC, f = 18.4 mm, 600–1050 nm, Ø3.98 mm waist.',
      role: 'Works as the laser collimator, but a 4 mm beam is larger than the AOM aperture; needs a reducing telescope or a smaller-beam port such as PAF2-5B.', link: 'https://www.thorlabs.com/item/paf-x-18-b', loc: '', owner: '', notes: '' },
    { id: 'L07', name: 'Ø½″ post holder, 50 mm', part: 'PH50E/M', brand: 'Thorlabs', qty: '6', model: 'postholder', mp: {}, status: 'use', bom: 'M03',
      specs: 'Aluminium, spring-loaded hex-locking thumbscrew, extra-wide relief cut for a two-line stable contact, 1/4″-20 (M6) tapped base, Ø12.7 mm pedestal post holder.',
      role: 'Post holders for the Ø½″ posts under the optics (the BOM listed 75 mm ones).', link: 'https://www.thorlabs.com/item/PH50E_M', loc: '', owner: '', notes: '' },
    { id: 'L08', name: 'Flat square mounting plate / adapter base block', part: '', brand: '', qty: '', model: 'baseplate', mp: {}, status: 'check', bom: '',
      specs: 'Solid square block, flat top, machined aluminium (raw finish), 4 threaded corner holes.',
      role: 'Unidentified; measure the size and hole spacing before using it as a mount base.', link: '', loc: '', owner: '', notes: '' },
    { id: 'L09', name: 'Square optical mount plate / lens-mount flange', part: '', brand: '', qty: '', model: 'baseplate', mp: { black: 1, ap: 1 }, status: 'check', bom: '',
      specs: 'Square base with a central circular aperture and retaining lip, black anodised, 4 corner holes, small set-screw hole in the rim, recessed ledge for a round optic.',
      role: 'Unidentified; possible filter or lens holder.', link: '', loc: '', owner: '', notes: '' },
    { id: 'L10', name: 'Optical rod clamp / post clamp', part: 'M-340-C', brand: 'Newport', qty: '', model: 'rodclamp', mp: {}, status: 'no', bom: '',
      specs: 'Fits 1.5 in. (38.1 mm) rods (M-40, M-41, 42, M-45), large knurled knob, anodised aluminium.',
      role: 'Ø1.5″ rod system, not our post system.', link: '', loc: '', owner: '', notes: '' },
    { id: 'L11', name: 'Cylindrical tube adapter / lens extension sleeve', part: '', brand: '', qty: '', model: 'tubeadapter', mp: {}, status: 'check', bom: '',
      specs: 'Stepped cylindrical body, internal thread at the top aperture, slotted set-screw collar, matte black anodised.',
      role: 'Unidentified; may fit a lens tube or beam tube.', link: '', loc: '', owner: '', notes: '' },
    { id: 'L12', name: 'Innov8tive Designs Cobra C-41 mm motor cross mount', part: 'INDC-MMS-41', brand: 'Innov8tive Designs', qty: '', model: 'generic', mp: {}, status: 'no', bom: '',
      specs: 'Replacement cross mount for Cobra 4120–4135 RC motors, 3 mm stamped aluminium, motor hole spacing 30 mm, firewall hole spacing 56 mm, M4 × 7.5 mm screws.',
      role: 'Radio-control hobby part: not relevant to the experiment.', link: 'https://gravesrc.com/indc-mms-41-innov8tive-designs-cobra-c-41mm-motor-cross-mount/', loc: '', owner: '', notes: '' },
    { id: 'L13', name: 'Circular mounting base plate / adapter flange', part: '', brand: '', qty: '', model: 'baseplate', mp: { round: 1, black: 1 }, status: 'check', bom: '',
      specs: 'Flat disc with several hole patterns and concentric alignment grooves, black anodised, unthreaded centre hole.',
      role: 'Unidentified adapter plate.', link: '', loc: '', owner: '', notes: '' },
    { id: 'L14', name: 'Mounted circular lens / optical filter assembly', part: '', brand: '', qty: '', model: 'lens', mp: {}, status: 'check', bom: '',
      specs: 'Threaded circular housing with a clear glass element behind an inner retaining ring, matte black anodised, fine threads for stacking on tubes.',
      role: 'Unidentified; check the glass and its coating.', link: '', loc: '', owner: '', notes: '' },
    { id: 'L15', name: 'Self-centering lens mount', part: 'LCM-1', brand: 'Newport', qty: '', model: 'lens', mp: {}, status: 'check', bom: 'O10',
      specs: 'Variable-size lens mount for optic diameters 3.2–27 mm, edge thickness 3.00–9.58 mm, optical axis height 37.8 mm, fixed, 8-32 and 1/4-20 threads.',
      role: 'Usable for small lenses (axis height 37.8 mm vs our 40 mm beam height; shim the post).', link: 'https://www.newport.com/p/LCM-1', loc: '', owner: '', notes: '' },
    { id: 'L16', name: 'Precision manual rotation stage, vertical mounting', part: 'PRO1/M', brand: 'Thorlabs', qty: '', model: 'rotstage', mp: {}, status: 'use', bom: 'O16, O07',
      specs: '360° continuous rotation with degree scale, micrometer fine adjustment, locking knob, vertical mounting bracket, through-hole, black anodised base.',
      role: 'Rotation mount for the Glan–Taylor or a waveplate.', link: '', loc: '', owner: '', notes: '' },
    { id: 'L17', name: 'Mounting base adaptor plate, 40 × 40 mm', part: 'M-B1-A', brand: 'Newport', qty: '', model: 'baseplate', mp: {}, status: 'check', bom: 'M04',
      specs: 'Aluminium, 40 × 40 mm.', role: 'Possible base for a stage or an AOM platform.', link: 'https://www.ntc-tech.com/products/newport-m-b1-a-mounting-base-adaptor-plate', loc: '', owner: '', notes: '' },
    { id: 'L18', name: 'Optical post assembly with circular base stand', part: '', brand: '', qty: '', model: 'postset', mp: {}, status: 'check', bom: 'M03',
      specs: 'Stainless post on a heavy circular pedestal, male threaded top stud (8-32, 1/4″-20, M4 or M6), 4 counterbored holes in the base.',
      role: 'The link in the inventory points to a thermowell product, so identify the real part first.', link: '', loc: '', owner: '', notes: '' },
    { id: 'L19', name: 'Fixed mount base plate (M-F-916 series)', part: 'M-F-916', brand: 'Newport', qty: '1', model: 'baseplate', mp: { black: 1, ap: 1 }, status: 'check', bom: '',
      specs: 'Black anodised aluminium, matte low-reflectivity finish, central through-hole, two counterbored mounting holes.',
      role: 'Possible fixed base for an optic or a small stage.', link: 'https://www.ebay.com/itm/226651631762', loc: '', owner: '', notes: '' },
    { id: 'L20', name: 'Goniometer stage', part: '07 GON 504', brand: 'Melles Griot', qty: '1', model: 'goniometer', mp: {}, status: 'use', bom: 'M04',
      specs: '40 × 40 mm, 16 mm high, ±20° tilt, 12 arcmin resolution, 3 kg load, brass with black oxide finish, preloaded dovetail bearing, knob adjust and lock, tilt axis at a fixed height above the surface.',
      role: 'Tilt stage for the Bragg angle of one AOM.', link: 'https://www.dougdeals.com/melles-griot-07-gon-504-goniometer-translation-stage-40x40mm-20-x-12-arcmin/', loc: '', owner: '', notes: '' },
    { id: 'L21', name: 'FiberPort collimator / alignment mount', part: 'PAF2-5B', brand: 'Thorlabs', qty: '', model: 'fibcol', mp: {}, status: 'use', bom: 'L05',
      specs: 'FC/APC and FC/PC, polarization maintaining, effective focal length 4.6 mm, NA 0.53, clear aperture 4.9 mm, output waist Ø1 mm (1/e²), divergence 1.087 mrad, mode field diameter 5 µm, lens H-LAK54, length 17.7 mm.',
      role: 'Laser collimator after the fibre isolator: a ~1 mm beam suits the AOM aperture.', link: 'https://www.thorlabs.com/item/paf2-5b', loc: '', owner: '', notes: '' },
    { id: 'L22', name: 'Fibre-to-fibre coupler bench (FiberBench)', part: 'FBP-B-FC', brand: 'Thorlabs', qty: '', model: 'fiberbench', mp: {}, status: 'check', bom: '',
      specs: '600–1050 nm (B coating), FC/PC and FC/APC, two FiberPort apertures with AR-coated aspheric lenses, clear cover, 1/4″-20 (M6) mounting slots, open deck for filters, polarizers or beamsplitters.',
      role: 'Optional: a free-space gap in the fibre where a filter or polarizer can be inserted.', link: '', loc: '', owner: '', notes: '' },
    { id: 'L23', name: 'Mounted optical filter / detector window on a pedestal base', part: '', brand: '', qty: '', model: 'generic', mp: {}, status: 'check', bom: '',
      specs: 'Vertical plate mount with a thick base block, raw aluminium, gold or dichroic yellow-green coated circular glass in the aperture, retaining faceplate with 4 screws.',
      role: 'Unidentified; check the coating and band.', link: '', loc: '', owner: '', notes: '' },
    { id: 'L24', name: 'Precision XYZ translation stage', part: 'XMO5A-S1-R', brand: '', qty: '1', model: 'xyzstage', mp: {}, status: 'use', bom: 'M04, L05',
      specs: 'Manual three-axis micrometer stage, aluminium, locking screws, flat platform with threaded holes. Serial 0305035 #17.',
      role: 'Cell holder positioning, or the fibre collimator or a photodiode.', link: 'https://www.amazon.in/Trimming-Platform-Aluminum-Measurement-Equipment/dp/B09N43B94J', loc: '', owner: '', notes: '' },
    { id: 'L25', name: 'Kinematic lens holder (M6)', part: 'M6', brand: '', qty: '', model: 'mirror', mp: {}, status: 'check', bom: 'O02',
      specs: 'Two-axis (pitch and yaw) kinematic mount with retaining ring, aluminium, stainless adjusters, vertical optic holder; aperture depends on the model.',
      role: 'Could serve as a mirror mount if it takes Ø1″ optics: measure the aperture.', link: 'https://www.ebay.com/itm/145802121163', loc: '', owner: '', notes: '' },
    { id: 'L26', name: 'Kinematic lens holder (M5)', part: 'M5', brand: '', qty: '', model: 'mirror', mp: {}, status: 'check', bom: 'O02',
      specs: 'Two-axis (pitch and yaw) kinematic mount with retaining ring, aluminium, stainless adjusters, vertical optic holder; aperture depends on the model.',
      role: 'Could serve as a mirror mount if it takes Ø1″ optics: measure the aperture.', link: 'https://www.ebay.com/itm/145802121163', loc: '', owner: '', notes: '' },
    { id: 'I01', name: 'Digital oscilloscope, 4 channels, 1 GHz (InfiniiVision 7000B)', part: 'DSO7104B', brand: 'Agilent (Keysight)', qty: '1', model: 'scope', mp: {}, status: 'use', bom: 'E02',
      specs: '1 GHz bandwidth, 4 analogue channels, 4 GSa/s, 8 Mpts memory, 12.1″ XGA display, up to 12 bits vertical resolution in high-resolution mode, external trigger input.',
      role: 'Probe photodiode (CH1), lock-box error signal (CH2), trigger from the function generator. Connect with BNC cables; check whether probes came with it.', link: 'https://valuetronics.com/products/dso7104b-agilent-digital-oscilloscope-used', loc: '', owner: '', notes: '' },
    { id: 'I02', name: 'Optical spectrum analyzer', part: '86142B', brand: 'Agilent (Keysight)', qty: '1', model: 'osa', mp: {}, status: 'use', bom: '',
      specs: '600–1700 nm, resolution bandwidth from 0.06 nm, dynamic range up to about 70 dB, wavelength reproducibility ±0.002 nm; accuracy is specified for 1480–1620 nm and about ±0.2 nm after user calibration over the full range.',
      role: 'Checks that the DFB runs on a single mode (side-mode suppression) and its coarse wavelength near 795 nm. It cannot find the Rb line, resolve AOM shifts or measure MHz linewidths.', link: 'https://wp.optics.arizona.edu/milster/wp-content/uploads/sites/48/2016/06/8614XBSeries.pdf', loc: '', owner: '', notes: '' },
    { id: 'I03', name: 'Laser diode current source and TEC temperature controller (ITC500 series)', part: 'ITC502', brand: 'Thorlabs', qty: '1', model: 'lctrl', mp: {}, status: 'use', bom: 'L03',
      specs: 'Laser: 0–200 mA, compliance > 6 V, noise < 1.5 µA rms (10 Hz–10 MHz), 24 h drift < 10 µA, analog modulation 20 mA/V with 0–500 kHz bandwidth (10 kΩ input). TEC: ±2 A, 16 W, > 8 V, thermistor input 10 Ω–19.9 kΩ, 24 h stability ≤ 0.5 Ω.',
      role: 'Drives and cools the 795 nm DFB (160 mA, 0.4 A TEC, 10 kΩ NTC). Set the current limit to 170 mA or lower before connecting. Its modulation input takes the lock box correction: 20 mA/V is about 28 GHz per volt, so attenuate the lock-box output about 100:1. Front-panel steps are coarse (10 µA is about 14 MHz, 1 Ω is about 65 MHz): tune coarsely by hand and let the lock do the fine tuning. The laser reads about 20 kΩ at 10 °C, so run at 15 °C or warmer. Check the output polarity and the cable against the butterfly mount.', link: 'https://www.thorlabs.com/catalogpages/417.pdf', loc: '', owner: '', notes: '' }
  ]
};
